<a href="https://colab.research.google.com/github/innysik222/Pandas-Numpy-ML-/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22practice_data_scaling_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Масштабирование данных

## Сегодня на практическом занятии:
1. Узнаем, как масштабировать данные
2. Поэкспериментируем с двумя моделями
3. Напишем свой класс для нормализации данных
4. Напишем свой класс для стандартизации данных

In [ ]:
#@title Установка нужных версий библиотек
!wget 'https://drive.google.com/uc?export=download&id=1oSFOP0j25OZAuhD8YXxyQXNTdr2lUdtn' -O requirements.txt
!pip install -r requirements.txt

--2022-05-26 11:25:51--  https://drive.google.com/uc?export=download&id=1oSFOP0j25OZAuhD8YXxyQXNTdr2lUdtn
Resolving drive.google.com (drive.google.com)... 74.125.197.113, 74.125.197.102, 74.125.197.100, ...
Connecting to drive.google.com (drive.google.com)|74.125.197.113|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0g-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/0l76s4ompgj0u8v1erbeg0gboa794ld8/1653564300000/14904333240138417226/*/1oSFOP0j25OZAuhD8YXxyQXNTdr2lUdtn?e=download [following]
--2022-05-26 11:25:51--  https://doc-0g-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/0l76s4ompgj0u8v1erbeg0gboa794ld8/1653564300000/14904333240138417226/*/1oSFOP0j25OZAuhD8YXxyQXNTdr2lUdtn?e=download
Resolving doc-0g-c0-docs.googleusercontent.com (doc-0g-c0-docs.googleusercontent.com)... 74.125.195.132, 2607:f8b0:400e:c09::84
Connecting to doc-0g-c0-docs.googleusercontent.com (doc-0g-c0-docs

In [ ]:
#pip install scipy

### Получение данных

Будем работать с набором данных `breast_cancer` из `sklearn`.

In [ ]:
from sklearn.datasets import load_breast_cancer
import pandas as pd


data = load_breast_cancer()

X = pd.DataFrame(data['data'], columns=data['feature_names'])
y = data['target']

X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0      17.9900       10.3800        122.8000  1001.0000           0.1184   
1      20.5700       17.7700        132.9000  1326.0000           0.0847   
2      19.6900       21.2500        130.0000  1203.0000           0.1096   
3      11.4200       20.3800         77.5800   386.1000           0.1425   
4      20.2900       14.3400        135.1000  1297.0000           0.1003   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0            0.2776          0.3001               0.1471         0.2419   
1            0.0786          0.0869               0.0702         0.1812   
2            0.1599          0.1974               0.1279         0.2069   
3            0.2839          0.2414               0.1052         0.2597   
4            0.1328          0.1980               0.1043         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                  0.0787  ...       25.3800        17.3300         184.6000   
1                  0.0567  ...       24.9900        23.4100         158.8000   
2                  0.0600  ...       23.5700        25.5300         152.5000   
3                  0.0974  ...       14.9100        26.5000          98.8700   
4                  0.0588  ...       22.5400        16.6700         152.2000   

   worst area  worst smoothness  worst compactness  worst concavity  \
0   2019.0000            0.1622             0.6656           0.7119   
1   1956.0000            0.1238             0.1866           0.2416   
2   1709.0000            0.1444             0.4245           0.4504   
3    567.7000            0.2098             0.8663           0.6869   
4   1575.0000            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                   0.1189  
1                0.1860          0.2750                   0.0890  
2                0.2430          0.3613                   0.0876  
3                0.2575          0.6638                   0.1730  
4                0.1625          0.2364                   0.0768  

[5 rows x 30 columns]

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

## KNN

### 1. До масштабирования

#### 1.1. Разбейте данные на обучение и тест

In [ ]:
# Ваш код здесь
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=10,test_size=0.2)
X_train.shape,X_test.shape


((455, 30), (114, 30))

#### 1.2. Обучите модель KNN

In [ ]:
#!pip uninstall scikit-learn -y

#!pip install -U scikit-learn

In [ ]:
# Ваш код здес
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)



KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

#### 1.3. Проверьте качество работы модели

По метрикам можете повторить эти занятия по [ссылке](https://youtube.com/playlist?list=PLkJJmZ1EJno6CLyvD4DHc32Fed6cPBHje)

In [ ]:
# Ваш код здесь
from sklearn.metrics import accuracy_score

pred_train = knn.predict(X_train)
pred_test = knn.predict(X_test)

print(f'Train acc {accuracy_score(y_train, pred_train)}')
print(f'Test acc {accuracy_score(y_test, pred_test)}')


Train acc 0.9494505494505494
Test acc 0.9210526315789473


### 2. Масштабирование


#### 2.1. Возьмите наиболее подходящий метод масштабирования из sklearn

In [ ]:
# Ваш код здесь
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()


##### 2.1.1. Обучите модель масштабирования

In [ ]:
# Ваш код здесь
mms.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

##### 2.1.2. Посмотрите, какие получились вспомогательные значения для этого подхода масштабирования

In [ ]:
import numpy as np
np.set_printoptions(suppress=True)

In [ ]:
# Ваш код здесь
mms.data_min_

array([  6.981    ,  10.38     ,  43.79     , 143.5      ,   0.05263  ,
         0.01938  ,   0.       ,   0.       ,   0.106    ,   0.04996  ,
         0.1115   ,   0.3602   ,   0.757    ,   7.228    ,   0.002667 ,
         0.002252 ,   0.       ,   0.       ,   0.007882 ,   0.0008948,
         7.93     ,  12.49     ,  50.41     , 185.2      ,   0.08125  ,
         0.03432  ,   0.       ,   0.       ,   0.1565   ,   0.05504  ])

In [ ]:
# Ваш код здесь
mms.data_max_


array([  28.11   ,   39.28   ,  188.5    , 2501.     ,    0.1634 ,
          0.3114 ,    0.4268 ,    0.2012 ,    0.304  ,    0.09744,
          2.873  ,    3.896  ,   21.98   ,  542.2    ,    0.03113,
          0.1064 ,    0.1535 ,    0.0409 ,    0.06146,    0.02286,
         36.04   ,   49.54   ,  251.2    , 4254.     ,    0.2226 ,
          1.058  ,    1.17   ,    0.291  ,    0.6638 ,    0.2075 ])

##### 2.1.3. Убедитесь, что значения такие же через подсчет статистик

1. Возьмите первый признак
2. Подсчитайте статистики, которые использовались в выбранном методе масштабирования
3. Сравните статистики

In [ ]:
# Ваш код здесь
X_train.min()
X_train.max()


mean radius                 28.1100
mean texture                39.2800
mean perimeter             188.5000
mean area                 2501.0000
mean smoothness              0.1634
mean compactness             0.3114
mean concavity               0.4268
mean concave points          0.2012
mean symmetry                0.3040
mean fractal dimension       0.0974
radius error                 2.8730
texture error                3.8960
perimeter error             21.9800
area error                 542.2000
smoothness error             0.0311
compactness error            0.1064
concavity error              0.1535
concave points error         0.0409
symmetry error               0.0615
fractal dimension error      0.0229
worst radius                36.0400
worst texture               49.5400
worst perimeter            251.2000
worst area                4254.0000
worst smoothness             0.2226
worst compactness            1.0580
worst concavity              1.1700
worst concave points        

Да, значения минимума и максимума совпадают.

#### 2.2. Преобразуйте обучающие данные с помощью модели масштабирования

In [ ]:
# Ваш код здесь
X_train_scaled=mms.transform(X_train)
X_train_scaled

array([[0.64456434, 0.65570934, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.32131194, 0.1       , 0.30592219, ..., 0.19938144, 0.2479795 ,
        0.08461236],
       [0.39703725, 0.4283737 , 0.38981411, ..., 0.50721649, 0.19534792,
        0.08684245],
       ...,
       [0.25363245, 0.06539792, 0.24289959, ..., 0.36769759, 0.30455352,
        0.13695396],
       [0.32509821, 0.23633218, 0.30854813, ..., 0.17539519, 0.15750049,
        0.11006166],
       [0.65071702, 0.71764706, 0.63513233, ..., 0.57010309, 0.25684999,
        0.17801391]])

#### 2.3. Преобразуйте тестовые данные с помощью модели масштабирования

In [ ]:
# Ваш код здесь
X_test_scaled=mms.transform(X_test)
X_test_scaled


array([[0.4012968 , 0.05224913, 0.40570797, ..., 0.62783505, 0.32544845,
        0.30145612],
       [0.1113162 , 0.4       , 0.10517587, ..., 0.08810997, 0.17149616,
        0.12390135],
       [0.31752568, 0.19688581, 0.30440191, ..., 0.24010309, 0.34654051,
        0.14410337],
       ...,
       [0.22807516, 0.23806228, 0.21746942, ..., 0.18405498, 0.23930613,
        0.17165158],
       [0.63225898, 0.38512111, 0.63651441, ..., 0.92268041, 0.78710822,
        0.31063886],
       [0.48790762, 0.40657439, 0.4879414 , ..., 0.52508591, 0.29607727,
        0.12987013]])

#### 2.4. Обучите еще раз модель KNN на масштабированных данных

In [ ]:
# Ваш код здесь
knn.fit(X_train_scaled,y_train)



KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

#### 2.5. Проверьте качество работы модели

По метрикам можете повторить эти занятия по [ссылке](https://youtube.com/playlist?list=PLkJJmZ1EJno6CLyvD4DHc32Fed6cPBHje)

In [ ]:
# Ваш код здесь
pred_train = knn.predict(X_train_scaled)
pred_test = knn.predict(X_test_scaled)

print(f'Train acc {accuracy_score(y_train, pred_train)}')
print(f'Test acc {accuracy_score(y_test, pred_test)}')



Train acc 0.9736263736263736
Test acc 0.9824561403508771


#### 2.6. Сделайте выводы

In [ ]:
# Ваши выводы здесь


## Дерево решений

### Получение данных

Будем работать с набором данных `california_housing` из `sklearn`.

In [ ]:
from sklearn.datasets import fetch_california_housing
import pandas as pd


data = fetch_california_housing()

X = pd.DataFrame(data['data'], columns=data['feature_names'])
y = data['target']

X.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252   41.0000    6.9841     1.0238    322.0000    2.5556   37.8800   
1  8.3014   21.0000    6.2381     0.9719   2401.0000    2.1098   37.8600   
2  7.2574   52.0000    8.2881     1.0734    496.0000    2.8023   37.8500   
3  5.6431   52.0000    5.8174     1.0731    558.0000    2.5479   37.8500   
4  3.8462   52.0000    6.2819     1.0811    565.0000    2.1815   37.8500   

   Longitude  
0  -122.2300  
1  -122.2200  
2  -122.2400  
3  -122.2500  
4  -122.2500

### 3. До масштабирования

#### 3.1. Разбейте данные на обучение и тест

In [ ]:
# Ваш код здесь
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=41, test_size=0.3)
X_train.shape, X_test.shape


((14448, 8), (6192, 8))

#### 3.2. Обучите модель дерево решений

In [ ]:
# Ваш код здесь
from sklearn.tree import DecisionTreeRegressor
tree = DecisionTreeRegressor(random_state=1, max_depth=9)
tree.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=9,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=1, splitter='best')

#### 3.3. Проверьте качество работы модели

По метрикам можете повторить это занятие по [ссылке](https://youtu.be/vh2smjQyhp8)

In [ ]:
# Ваш код здесь
pred_train_tree=tree.predict(X_train)
pred_test_tree=tree.predict(X_test)
print(f'R2 Train{r2_score(pred_train_tree,y_train)}')
print(f'R2 Test:{r2_score(pred_test_tree,y_test)}')


R2 Train0.7464030135902033
R2 Test:0.6210838696771732


### 4. Масштабирование


#### 4.1. Возьмите метод масштабирования из sklearn

In [ ]:
# Ваш код здесь
from sklearn.preprocessing import StandardScaler
ssc=StandardScaler()


##### 4.1.1. Обучите модель масштабирования

In [ ]:
# Ваш код здесь
ssc.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

##### 4.1.2. Посмотрите, какие получились вспомогательные значения для этого подхода масштабирования

In [ ]:
# Ваш код здесь
ssc.mean_

array([   3.87458063,   28.55689369,    5.44047656,    1.09833156,
       1421.95992525,    3.01953686,   35.63900678, -119.57395695])

In [ ]:
# Ваш код здесь
ssc.scale_

array([   1.90658911,   12.58185061,    2.62431219,    0.51194472,
       1141.70272772,    6.59411622,    2.135789  ,    2.00517733])

##### 4.1.3. Убедитесь, что значения такие же через подсчет статистик

1. Возьмите первый признак
2. Подсчитайте статистики, которые использовались в выбранном методе масштабирования
3. Сравните статистики

In [ ]:
# Ваш код здесь
X_train.mean()
X_train.std()


MedInc          1.9067
HouseAge       12.5823
AveRooms        2.6244
AveBedrms       0.5120
Population   1141.7422
AveOccup        6.5943
Latitude        2.1359
Longitude       2.0052
dtype: float64

Да, значения среднего и стандартного отклонения совпадают.

#### 4.2. Преобразуйте обучающие данные с помощью модели масштабирования

In [ ]:
# Ваш код здесь
X_train_transform=ssc.transform(X_train)


#### 4.3. Преобразуйте тестовые данные с помощью модели масштабирования

In [ ]:
# Ваш код здесь
X_test_transform=ssc.transform(X_test)


#### 4.4. Обучите еще раз модель на масштабированных данных

In [ ]:
# Ваш код здесь
tree.fit(X_train_transform,y_train)


DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=9,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=1, splitter='best')

#### 4.5. Проверьте качество работы модели

По метрикам можете повторить это занятие по [ссылке](https://youtu.be/vh2smjQyhp8)

In [ ]:
# Ваш код здесь
pred_train_tree=tree.predict(X_train_transform)
pred_test_tree=tree.predict(X_test_transform)
print(f'R2 Train{r2_score(pred_train_tree,y_train)}')
print(f'R2 Test:{r2_score(pred_test_tree,y_test)}')


R2 Train0.7464030135902033
R2 Test:0.620800245207868


#### 4.6. Сделайте выводы

In [ ]:
# Ваши выводы здесь


### 5. Свой класс MinMaxScaler

В этом пункте напишите с нуля свою модель масштабирования данных.


#### 5.1. Реализуйте в классе метод fit, который высчитывает минимальное и максимальное значения в признаках

In [ ]:
# Ваш код здесь

mins_train=X_train.min()
maxs_train=X_train.max()
mins_test=X_test.min()
maxs_test=X_test.max()
X__train_scaler=(X_train-mins_train)/(maxs_train-mins_train)
X_test_scaler=(X_test-mins_test)/(maxs_test-mins_test)

#### 5.2. Проверьте, что данный метод работает корректно на выборке с предыдущего пункта

In [ ]:
# Ваш код здесь
display(mins_train,maxs_train)

MedInc          0.499900
HouseAge        1.000000
AveRooms        0.846154
AveBedrms       0.375000
Population      3.000000
AveOccup        0.692308
Latitude       32.550000
Longitude    -124.300000
dtype: float64

MedInc           15.000100
HouseAge         52.000000
AveRooms        141.909091
AveBedrms        34.066667
Population    35682.000000
AveOccup        599.714286
Latitude         41.950000
Longitude      -114.310000
dtype: float64

#### 5.3. Реализуйте в классе метод transform, который преобразует входную выборку

In [ ]:
# Ваш код здесь
X__train_scaler.describe()



#### 5.4. Проверьте, что данный метод работает корректно

In [ ]:
# Ваш код здесь
X__train_scaler.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  14448.000000  14448.000000  14448.000000  14448.000000  14448.000000   
mean       0.232733      0.540331      0.032569      0.021469      0.039770   
std        0.131492      0.246711      0.018604      0.015196      0.032000   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.142089      0.333333      0.025467      0.018721      0.022002   
50%        0.209618      0.549020      0.031119      0.019998      0.032624   
75%        0.292918      0.705882      0.036966      0.021477      0.048215   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

           AveOccup      Latitude     Longitude  
count  14448.000000  14448.000000  14448.000000  
mean       0.003885      0.328618      0.473077  
std        0.011009      0.227219      0.200725  
min        0.000000      0.000000      0.000000  
25%        0.002895      0.147872      0.251251  
50%        0.003537      0.181915      0.580581  
75%        0.004314      0.548936      0.629630  
max        1.000000      1.000000      1.000000

### 6. Свой класс StandardScaler

В этом пункте напишите с нуля еще одну модель масштабирования данных.


#### 5.1. Реализуйте в классе метод fit, который высчитывает среднее и стандартное отклонение в признаках

In [ ]:
# Ваш код здесь
means=X_train.mean()
stds=X_train.std()


#### 5.2. Проверьте, что данный метод работает корректно на выборке с предыдущего пункта

In [ ]:
# Ваш код здесь
display(means,stds)

MedInc           3.874581
HouseAge        28.556894
AveRooms         5.440477
AveBedrms        1.098332
Population    1421.959925
AveOccup         3.019537
Latitude        35.639007
Longitude     -119.573957
dtype: float64

MedInc           1.906655
HouseAge        12.582286
AveRooms         2.624403
AveBedrms        0.511962
Population    1141.742241
AveOccup         6.594344
Latitude         2.135863
Longitude        2.005247
dtype: float64

#### 5.3. Реализуйте в классе метод transform, который преобразует входную выборку

In [ ]:
# Ваш код здесь
X_train_standard=(X_train-means)/stds

#### 5.4. Проверьте, что данный метод работает корректно

In [ ]:
pd.set_option('display.float_format', lambda x: '%0.4f' % x)

In [ ]:
# Ваш код здесь
X_train_standard.describe()


MedInc   HouseAge   AveRooms  AveBedrms  Population   AveOccup  \
count 14448.0000 14448.0000 14448.0000 14448.0000  14448.0000 14448.0000   
mean     -0.0000     0.0000    -0.0000    -0.0000      0.0000    -0.0000   
std       1.0000     1.0000     1.0000     1.0000      1.0000     1.0000   
min      -1.7699    -2.1901    -1.7506    -1.4129     -1.2428    -0.3529   
25%      -0.6894    -0.8390    -0.3818    -0.1808     -0.5553    -0.0899   
50%      -0.1758     0.0352    -0.0780    -0.0968     -0.2233    -0.0316   
75%       0.4577     0.6710     0.2363     0.0005      0.2639     0.0390   
max       5.8351     1.8632    51.9999    64.3960     30.0068    90.4858   

        Latitude  Longitude  
count 14448.0000 14448.0000  
mean      0.0000     0.0000  
std       1.0000     1.0000  
min      -1.4463    -2.3568  
25%      -0.7955    -1.1051  
50%      -0.6456     0.5356  
75%       0.9696     0.7799  
max       2.9548     2.6251

## Резюме 

Сегодня на практическом занятии:
1. Узнали, как масштабировать данные
2. Поэкспериментировали с двумя моделями
3. Написали свой класс для нормализации данных
4. Написали свой класс для стандартизации данных

## Резюме 

Сегодня на практическом занятии:
1. Узнали, как масштабировать данные
2. Поэкспериментировали с двумя моделями
3. Написали свой класс для нормализации данных
4. Написали свой класс для стандартизации данных

**Муррр** ♥